### ISSUE TITLE
IKnowWhatImDoing-3.0.0-fabric on the mod page is listed as being compatible with 1.12

### ISSUE THREAD

**Issue by aaronhowser1** [ChloeDawn/IKnowWhatImDoing#2]
![](https://cdn.discordapp.com/attachments/730325204550811708/737162860160876576/unknown.png)

Twitch showed an update for IKWID so I downloaded it, and it's not even for the same modloader *or* minecraft version. It doesn't load at all, nor does it crash.

**Comment by ChloeDawn** [comment]
It was marked as compatible with 1.12 as it is binary-compatible with the game code. It would just require Fabric Loader to be available for 1.12 (which I believe someone has done this?). If you loaded it on Forge, then yes, it will do nothing, as it is a Fabric mod, and in 1.12 Forge has no warning for Fabric JARs.

**Comment by aaronhowser1** [comment]
But leaving it as it is makes it always say there's an update for IKWID, when there isn't. This version, which does not work on 1.12, says it works on 1.12, but is a newer version, so it is the version that is used when you download the mod with CurseForge.

**Comment by ChloeDawn** [comment]
I guess I will unmark it... but that is a problem with CurseForge not IKWID. It should not report updates when the file is targeting Fabric and the modpack is targeting Forge...
