### ISSUE TITLE
Doesn't seem to be working in v1.16.5

### ISSUE THREAD

**Issue by AngleWyrm10** [ChloeDawn/IKnowWhatImDoing#4]
Version 3.1.0-Forge
Minecraft v1.16.5
Forge v36.1.7
![tutorial](https://user-images.githubusercontent.com/55937426/122298689-ec10f680-ceb1-11eb-90e3-4a1bbfef48ae.png)

Modlist
![modlist](https://user-images.githubusercontent.com/55937426/122298949-38f4cd00-ceb2-11eb-9075-27b9b759cdaf.png)

**Comment by ChloeDawn** [comment]
Due to a limitation in Forge, IKWID is unable to save changes to the options.txt at startup, and therefore only works when an options.txt has not previously been created. I can look into working around this limitation. Thank you for bringing this to my attention!

**Comment by ChloeDawn** [comment]
Fixed in [3.2.0](https://www.curseforge.com/minecraft/mc-mods/i-know-what-im-doing/files/3369234)
