### ISSUE TITLE
Could you make this remove the recipe book in the 1.16.5 version?

### ISSUE THREAD

**Issue by vizthex123** [ChloeDawn/IKnowWhatImDoing#5]
Perhaps as a config option? I find the thing annoying af, and the [no recipe book](https://www.curseforge.com/minecraft/mc-mods/no-recipe-book) mod hasn't been ported yet.

**Comment by ChloeDawn** [comment]
For recipe book removal in 1.16, I recommend checking out [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench), which implements it in a better fashion.

**Comment by vizthex123** [comment]
Yeah, I found that out recently. Annoying how it isn't on by default though, ah well.
