### ISSUE TITLE
1.18.2 Forge 40.0.24 Had to press that button

### ISSUE THREAD

**Issue by Knito58** [ChloeDawn/IKnowWhatImDoing#7]
I installed this mod today hoping to bypass the warning. I still had to press that annoying "I know what I'm doing" button.

Minecraft 1.18.2 Single Player
Forge 40.0.24

Mods: a lot

**Comment by ChloeDawn** [comment]
This mod suppresses [in-game tutorial hints](https://minecraft.gamepedia.com/Tutorial_hints), not the experimental settings warning. I apologize for the confusing name overlap, this mod was created before that screen existed.

**Comment by Knito58** [comment]
Oh - ok then. Thank you. Will keep this mod as that hints are annoying, too.
