### ISSUE TITLE
Incompatible with Forge 41.0.64 and above

### ISSUE THREAD

**Issue by AmyRose1288** [ChloeDawn/IKnowWhatImDoing#9]
java.lang.ClassNotFoundException: net.minecraftforge.client.event.ScreenOpenEvent

Forge 41.1.0 Minecraft 1.19 No Optifine Installed
[latest.log](https://github.com/ChloeDawn/IKnowWhatImDoing/files/9239075/latest.log)
[crash-2022-08-02_12.33.07-fml.txt](https://github.com/ChloeDawn/IKnowWhatImDoing/files/9239076/crash-2022-08-02_12.33.07-fml.txt)

**Comment by ChloeDawn** [comment]
Fixed in 5.1.1 [ [CurseForge](https://www.curseforge.com/minecraft/mc-mods/i-know-what-im-doing/files/3912390) | [Modrinth](https://modrinth.com/mod/i-know-what-im-doing/version/5.1.1-forge) ]
